
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.gargoylesoftware.htmlunit.BrowserVersion;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import org.openqa.selenium.TimeoutException;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class ModifyTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		int browser = 0; // 0: firefox, 1: chrome, 2: htmlunit,...
	    Boolean headless = true;

	    switch (browser) {
	    case 0:
	    	if (System.getProperty("os.name").toLowerCase().contains("win"))
	    		System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
	    	FirefoxOptions firefoxOptions = new FirefoxOptions(); 
	    	firefoxOptions.addArguments("--start-maximized");
	    	firefoxOptions.addArguments("--disable-popup-blocking");
	    	firefoxOptions.addArguments("--disable-extensions");
	    	if (headless) firefoxOptions.addArguments("--headless");
	        driver = new FirefoxDriver(firefoxOptions);
	    	break;
	    case 1:
	    	if (System.getProperty("os.name").toLowerCase().contains("win"))
	    		System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
	    	ChromeOptions chromeOptions = new ChromeOptions();
		    chromeOptions.addArguments("--start-maximized");
		    chromeOptions.addArguments("--disable-popup-blocking");
		    chromeOptions.addArguments("--disable-extensions");
		    if (headless) chromeOptions.addArguments("--headless");
		    driver = new ChromeDriver(chromeOptions);
	    	break;
	    case 2:
	    	driver = new HtmlUnitDriver(BrowserVersion.FIREFOX, true);
	    	break;
	    default:
	    	fail("Please select a browser");
	    	break;
	    }

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

		// Configurar timeouts
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().setScriptTimeout(Duration.ofSeconds(30));
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		driver.findElement(By.id("input-vaadin-text-field-6")).sendKeys("admin");
		driver.findElement(By.id("input-vaadin-password-field-7")).sendKeys("admin");
		driver.findElement(By.cssSelector("vaadin-button:nth-child(2)")).click();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void ModifyFailBlankName() {
		// Test name: 12.Modify_Fail_BlankName
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | a
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("a");
		// 5 | sendKeys | id=input-vaadin-text-field-23 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		// 6 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 7 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 8 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 9 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 10 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 11 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-3 | First name cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-3")).getText(),
				is("First name cannot be blank"));
	}

	@Test
	public void ModifyFailBlankLastName() {
		// Test name: 13.Modify_Fail_BlankLastName
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | a
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("a");
		// 6 | sendKeys | id=input-vaadin-text-field-24 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		// 7 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 8 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 9 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 10 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 11 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-6 | Last name cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-6")).getText(),
				is("Last name cannot be blank"));
	}

	@Test
	public void ModifyFailBlankMail() {
		// Test name: 14.Modify_Fail_BlankMail
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | a
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("a");
		// 7 | sendKeys | id=input-vaadin-text-field-25 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		// 8 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 9 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 10 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 11 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-9 | Email cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-9")).getText(),
				is("Email cannot be blank"));
	}

	@Test
	public void ModifyFailWrongMail() {
		// Test name: 15.Modify_Fail_WrongMail
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito");
		// 7 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 8 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 9 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 10 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 11 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 12 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 13 | assertText | id=error-message-vaadin-text-field-9 | must be a
		// well-formed email address
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-9")).getText(),
				is("must be a well-formed email address"));
	}

	@Test
	public void ModifyFailBlankPhone() {
		// Test name: 16.Modify_Fail_BlankPhone
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 7 | type | id=input-vaadin-text-field-26 | a
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("a");
		// 8 | sendKeys | id=input-vaadin-text-field-26 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		// 9 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 10 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 11 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-12 | Phone cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-12")).getText(),
				is("Phone cannot be blank"));
		
	}

	@Test
	public void ModifyFailBlankDate() {
		// Test name: 17.Modify_Fail_BlankDate
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 7 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 8 | type | id=input-vaadin-date-picker-27 | a
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("a");
		// 9 | sendKeys | id=input-vaadin-date-picker-27 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys(Keys.DELETE);
		// 10 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 11 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-date-picker-15 | Date cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-date-picker-15")).getText(),
				is("Date cannot be blank"));
	}

	@Test
	public void ModifyFailBlankOccupation() {
		// Test name: 18.Modify_Fail_BlankOccupation
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 7 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 8 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 9 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 10 | type | id=input-vaadin-text-field-28 | a
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("a");
		// 11 | sendKeys | id=input-vaadin-text-field-28 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		// 12 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-18 | Occupation cannot
		// be blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-18")).getText(),
				is("Occupation cannot be blank"));
	}

	@Test
	public void ModifyFailBlankRole() {
		// Test name: 19.Modify_Fail_BlankRole
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 7 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 8 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 9 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 10 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 11 | type | id=input-vaadin-text-field-29 | a
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("a");
		// 12 | sendKeys | id=input-vaadin-text-field-29 | ${KEY_DELETE}
		driver.findElement(By.cssSelector("html")).click();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys(Keys.DELETE);
		driver.findElement(By.cssSelector("html")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		// 14 | assertText | id=error-message-vaadin-text-field-21 | Role cannot be
		// blank
		assertThat(driver.findElement(By.id("error-message-vaadin-text-field-21")).getText(),
				is("Role cannot be blank"));
	}

	@Test
	public void Modifysucces() {
		// Test name: 20.Modify_succes
		// Step # | name | target | value
		// 1 | open | https://my-app-1715855750474.azurewebsites.net/login |
		driver.get("https://my-app-1715855750474.azurewebsites.net/login");
		// 2 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
		// 3 | waitForElementEditable | id=input-vaadin-text-field-23 | 5000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 4 | type | id=input-vaadin-text-field-23 | Jesus
		driver.findElement(By.id("input-vaadin-text-field-23")).clear();
		driver.findElement(By.id("input-vaadin-text-field-23")).sendKeys("Jesus");
		// 5 | type | id=input-vaadin-text-field-24 | Muñoz
		driver.findElement(By.id("input-vaadin-text-field-24")).clear();
		driver.findElement(By.id("input-vaadin-text-field-24")).sendKeys("Muñoz");
		// 6 | type | id=input-vaadin-text-field-25 | jesusito@gmail.com
		driver.findElement(By.id("input-vaadin-text-field-25")).clear();
		driver.findElement(By.id("input-vaadin-text-field-25")).sendKeys("jesusito@gmail.com");
		// 7 | type | id=input-vaadin-text-field-26 | 987654321
		driver.findElement(By.id("input-vaadin-text-field-26")).clear();
		driver.findElement(By.id("input-vaadin-text-field-26")).sendKeys("987654321");
		// 8 | type | id=input-vaadin-date-picker-27 | 5/6/2000
		driver.findElement(By.id("input-vaadin-date-picker-27")).clear();
		driver.findElement(By.id("input-vaadin-date-picker-27")).sendKeys("5/6/2000");
		// 9 | click | css=html |
		driver.findElement(By.cssSelector("html")).click();
		// 10 | type | id=input-vaadin-text-field-28 | IT
		driver.findElement(By.id("input-vaadin-text-field-28")).clear();
		driver.findElement(By.id("input-vaadin-text-field-28")).sendKeys("IT");
		// 11 | type | id=input-vaadin-text-field-29 | Worker
		driver.findElement(By.id("input-vaadin-text-field-29")).clear();
		driver.findElement(By.id("input-vaadin-text-field-29")).sendKeys("Worker");
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 13 | click | css=vaadin-button:nth-child(1) |
		driver.findElement(By.cssSelector("vaadin-button:nth-child(1)")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(4));
			try { wait.until(driver -> false); } catch (TimeoutException e) {}
		}
		// 14 | assertText | css=vaadin-grid-cell-content:nth-child(33) | Jesus
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).getText(), is("Jesus"));
		// 15 | assertText | css=vaadin-grid-cell-content:nth-child(34) | Muñoz
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(34)")).getText(), is("Muñoz"));
		// 16 | assertText | css=vaadin-grid-cell-content:nth-child(35) |
		// jesusito@gmail.com
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(35)")).getText(),
				is("jesusito@gmail.com"));
		// 17 | assertText | css=vaadin-grid-cell-content:nth-child(36) | 987654321
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(36)")).getText(),
				is("987654321"));
		// 18 | assertText | css=vaadin-grid-cell-content:nth-child(37) | 2000-05-06
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(37)")).getText(),
				is("2000-05-06"));
		// 19 | assertText | css=vaadin-grid-cell-content:nth-child(38) | IT
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(38)")).getText(), is("IT"));
		// 20 | assertText | css=vaadin-grid-cell-content:nth-child(39) | Worker
		assertThat(driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(39)")).getText(),
				is("Worker"));
		// 21 | click | css=vaadin-grid-cell-content:nth-child(33) |
		driver.findElement(By.cssSelector("vaadin-grid-cell-content:nth-child(33)")).click();
	}
}
